# Generated by Django 3.1.4 on 2021-02-25 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('Discipline', models.CharField(choices=[('power', 'POWER'), ('telecom', 'TELECOM'), ('common', 'COMMON')], default='telecom', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Youtube', models.CharField(default='https://youtube.com', max_length=300)),
                ('Drive', models.CharField(max_length=300, null=True)),
                ('Date', models.DateTimeField(null=True, verbose_name='Date In')),
                ('Lecture_Number', models.FloatField(null=True)),
                ('Course', models.ForeignKey(default='Microprocessor II', on_delete=django.db.models.deletion.CASCADE, to='ElectricalSem8App.course')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('Format', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=100)),
                ('Drive', models.CharField(max_length=300, null=True)),
                ('Course', models.ForeignKey(default='Microprocessor II', on_delete=django.db.models.deletion.CASCADE, to='ElectricalSem8App.course')),
            ],
        ),
    ]
