# Generated by Django 2.2.19 on 2021-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='About',
            field=models.TextField(blank=True, default='Nothing to show yet', max_length=100000),
        ),
    ]
