# Generated by Django 2.2.19 on 2021-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=500)),
                ('Week', models.IntegerField()),
                ('Method', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Discipline',
            field=models.CharField(choices=[('power', 'POWER'), ('telecom', 'TELECOM'), ('did not decide yet', 'DID NOT DECIDE YET')], default='telecom', max_length=100),
        ),
    ]
