# Generated by Django 2.2.19 on 2021-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0007_auto_20210307_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Description',
            field=models.CharField(default='no description', max_length=100),
            preserve_default=False,
        ),
    ]
