# Generated by Django 2.2.19 on 2021-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0008_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='LinuxGroup',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
