# Generated by Django 3.2 on 2021-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0010_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='Name',
            field=models.CharField(default='No name', max_length=50),
        ),
        migrations.AddField(
            model_name='viewer',
            name='file_id',
            field=models.IntegerField(default=0),
        ),
    ]
