# Generated by Django 2.2.19 on 2021-05-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0012_auto_20210425_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.CharField(default='', max_length=100)),
                ('Votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='viewer',
            name='Schedule',
            field=models.CharField(default='', max_length=100),
        ),
    ]
