# Generated by Django 2.2.19 on 2021-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0013_auto_20210513_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='Auto',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Data_Analysis',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Economy',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Instrumentation',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Lab4',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Lab5',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Machine',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Micro',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Miniproject',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='OS',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Synthesis',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Telecom',
            field=models.IntegerField(default=-1),
        ),
    ]
