# Generated by Django 2.2.19 on 2021-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0014_auto_20210705_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='Rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='viewer',
            name='Total',
            field=models.IntegerField(default=-1),
        ),
    ]
