# Generated by Django 2.2.19 on 2021-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectricalSem8App', '0015_auto_20210705_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='group',
            name='Week',
            field=models.CharField(max_length=20),
        ),
    ]
